#!/usr/bin/env ruby

 arr = []
 `grep -rn --color '#{ARGV[0]}' #{ARGV[1..-1].join(" ")}|grep -v swp`.each do     |l|
   puts l
   arr << [l.gsub(/:.*$/, "").strip, l.gsub(/^.*?:/, "").gsub(/:.*$/, "").strip]
 end
 
 puts "------------------------\n\n" 
 
 arr.each do |a| 
   puts "opening #{a[0]} at #{a[1]}" 
   `gvim #{a[0]} +#{a[1]}`
 end

