#!/usr/bin/env bash

rm -rf ~/.rbenv

git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

mkdir -p ~/.rbenv/plugins

git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
git clone https://github.com/rkh/rbenv-update.git ~/.rbenv/plugins/rbenv-update
git clone git://github.com/tpope/rbenv-aliases.git ~/.rbenv/plugins/rbenv-aliases
git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
git clone https://github.com/sstephenson/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems

echo bundler >> ~/.rbenv/default-gems

eval "$(rbenv init -)"
rbenv alias --auto
