#!/bin/bash

gem install github-markup \
            ap \
            yard \
            ripl \
            ripl-rails \
            ripl-rack \
            ripl-debug \
            ripl-color_error \
            ripl-color_streams \
            ripl-color_result \
            ripl-auto_indent 
