#!/usr/bin/env bash


brew install node

cd /opt

git clone git://github.com/etsy/statsd.git .

cd /opt/statsd

cp exampleConfig.js localConfig.js
vi localConfig.js (update the graphiteHost to be 0.0.0.0)

node stats.js localConfig.js