#!/usr/bin/env ruby

def link(to, from, title)
  to = File.expand_path(to)
  from = File.expand_path(from)

  `ln -s #{from} #{to}` and puts "Linked #{title}" unless File.exists?(to)
end

`ls ~/dotfiles`.split.each do |f|
  to = File.expand_path("~/.#{f}")
  from = File.expand_path("~/dotfiles/#{f}")
  `ln -s #{from} #{to}` and puts "Linked .#{f}" unless File.exists?(to) || File.directory?(from)
end

`ls ~/Dropbox/dotfiles`.split.each do |f|
  link "~/.#{f}", File.expand_path("~/Dropbox/dotfiles/#{f}"), f
end

`ls ~/dotfiles/config`.split.each do |f|
  to = File.expand_path("~/.config/#{f}")
  from = File.expand_path("~/dotfiles/config/#{f}")
  `ln -s #{from} #{to}` and puts "Linked .config/#{f}" unless File.exists?(to)
end


`mkdir -p ~/.passenger/standalone`
link "~/.lein", "~/dotfiles/lein", ".lein"
link "~/.passenger/standalone/config", "~/dotfiles/passenger/standalone/config", "passenger config"
