#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'
require 'bson'

if ARGV.size < 2
  puts "usage: mongo-dummy-data <db> <collection> [<dummy data>]\n\n"
  exit 
end

collection = Mongo::Connection.new.db(ARGV[0]).collection(ARGV[1])
if ARGV[3]
  data = eval ARGV[3]
else
  data = {:foo => 'bar'}
end

1000000.times {collection.insert(:foo => 'bar')}
