#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'
require 'bson'
require 'faker'

if ARGV.size < 2
  puts "usage: mongo-dummy-data <db> <collection> [<dummy data>]\n\n"
  exit 
end

collection = Mongo::Connection.new.db(ARGV[0]).collection(ARGV[1])
if ARGV[3]
  data = eval ARGV[3]
else
  data = {:foo => 'bar'}
end

1000000.times {collection.insert(:foo => 'bar', 
  :name => Faker::Name.name, 
  :phone => Faker::PhoneNumber.phone_number,
  :company => { :bs => Faker::Company.bs,
                :name => Faker::Company.name,
                :address => { :city => Faker::Address.city,
                  :street => Faker::Address.street_name,
                  :state => Faker::Address.us_state,
                  :zip => Faker::Address.zip_code
                }
              })}
