#!/usr/bin/env ruby

ARGV.unshift 'rspec'
require 'rubygems'
gem 'zeus'
load Gem.bin_path('zeus', 'zeus')

# Edit Configurations... => Defaults => RSpec
# Use Custom Script => path to this file
# Environment Variables => RUBYLIB = /Applications/RubyMine\ EAP.app/rb/testing/patch/common:/Applications/RubyMine\ EAP.app/rb/testing/patch/bdd:/Applications/RubyMine\ EAP.app/rb/testing/patch/common:/Applications/RubyMine\ EAP.app/rb/testing/patch/testunit

